# Generated by Django 4.2.28 on 2026-08-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recolte', '0002_producteur_type_prod_alter_cueillette_id_and_more'),
        ('appro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='producteur_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptions_directes', to='recolte.producteur', verbose_name='Producteur externe'),
        ),
        migrations.AlterField(
            model_name='articlestock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
