export const chantiers = [
  {
    id: 'CH-08',
    nom: 'Résidence Sotuba',
    avancement: 65,
    statut: 'En cours' as const,
    client: 'Particulier — M. Sangaré',
    adresse: 'Sotuba, Bamako',
    chefDeChantier: 'Boubacar Traoré',
    dateDebut: '3 juin 2024',
    dateFinPrevue: '15 nov. 2024',
    etapes: [
      { nom: 'Fondations', avancement: 100 },
      { nom: 'Gros œuvre', avancement: 80 },
      { nom: 'Second œuvre', avancement: 40 },
      { nom: 'Finitions', avancement: 0 },
    ],
  },
  {
    id: 'CH-09',
    nom: 'Entrepôt ACI',
    avancement: 20,
    statut: 'En cours' as const,
    client: 'Sarl Distribution Mali',
    adresse: 'ACI 2000, Bamako',
    chefDeChantier: 'S. Coulibaly',
    dateDebut: '12 août 2024',
    dateFinPrevue: '30 janv. 2025',
    etapes: [
      { nom: 'Fondations', avancement: 60 },
      { nom: 'Gros œuvre', avancement: 10 },
      { nom: 'Second œuvre', avancement: 0 },
      { nom: 'Finitions', avancement: 0 },
    ],
  },
  {
    id: 'CH-07',
    nom: 'Villa Badalabougou',
    avancement: 100,
    statut: 'Terminé' as const,
    client: 'Particulier — Mme Keïta',
    adresse: 'Badalabougou, Bamako',
    chefDeChantier: 'Boubacar Traoré',
    dateDebut: '2 janv. 2024',
    dateFinPrevue: '20 mai 2024',
    etapes: [
      { nom: 'Fondations', avancement: 100 },
      { nom: 'Gros œuvre', avancement: 100 },
      { nom: 'Second œuvre', avancement: 100 },
      { nom: 'Finitions', avancement: 100 },
    ],
  },
];
