# Generated by Django 6.1 on 2026-08-26 10:27

import comptes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='rh, finance, bdm, daily...', max_length=32, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom affiche')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('groupe', models.CharField(blank=True, help_text="Intitule de la section du menu : « Board », « Applications metier »... Le libelle sert directement d'en-tete, pour qu'ajouter une section ne demande pas de toucher au front.", max_length=60, verbose_name='Groupe')),
                ('chemin', models.CharField(blank=True, help_text='Par exemple /daily, la page ouverte depuis le tableau de bord.', max_length=100, verbose_name='Chemin dans le shell')),
                ('prefixe_api', models.CharField(blank=True, help_text='Par exemple /api/daily, route servie par la passerelle.', max_length=100, verbose_name="Prefixe d'API")),
                ('roles_disponibles', models.JSONField(blank=True, default=list, help_text="Liste d'objets code/libelle propres a cette application.", verbose_name='Roles disponibles')),
                ('couleur', models.CharField(blank=True, max_length=9, verbose_name='Couleur')),
                ('ordre', models.PositiveSmallIntegerField(default=100, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Application active')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'application',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('identifiant', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Identifiant de connexion')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prenom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Telephone')),
                ('fonction', models.CharField(blank=True, max_length=150, verbose_name='Fonction')),
                ('est_actif', models.BooleanField(default=True, help_text='Un compte inactif ne peut plus se connecter nulle part.', verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name="Acces a l'administration Django")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Derniere connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateur',
                'ordering': ['nom', 'prenom'],
            },
            managers=[
                ('objects', comptes.models.GestionnaireUtilisateur()),
            ],
        ),
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_saisi', models.CharField(max_length=150, verbose_name='Identifiant saisi')),
                ('reussie', models.BooleanField(default=False, verbose_name='Reussie')),
                ('motif', models.CharField(blank=True, max_length=100, verbose_name="Motif de l'echec")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('agent', models.CharField(blank=True, max_length=300, verbose_name='Navigateur')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connexion',
                'verbose_name_plural': 'Journal des connexions',
                'db_table': 'journal_connexion',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionJeton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_jeton', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Identifiant du jeton (jti)')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('expire_le', models.DateTimeField(verbose_name='Expire le')),
                ('revoque_le', models.DateTimeField(blank=True, null=True, verbose_name='Revoque le')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('agent', models.CharField(blank=True, max_length=300, verbose_name='Navigateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'session_jeton',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list, help_text="Codes de roles, pris dans roles_disponibles de l'application.", verbose_name='Roles')),
                ('active', models.BooleanField(default=True, verbose_name='Habilitation active')),
                ('accordee_le', models.DateTimeField(auto_now_add=True, verbose_name='Accordee le')),
                ('accordee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitations_accordees', to=settings.AUTH_USER_MODEL, verbose_name='Accordee par')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitations', to='comptes.application', verbose_name='Application')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Habilitation',
                'verbose_name_plural': 'Habilitations',
                'db_table': 'habilitation',
                'ordering': ['application__ordre'],
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'application'), name='une_habilitation_par_application')],
            },
        ),
    ]
