# Generated by Django 6.1 on 2026-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitation',
            name='identifiant_local',
            field=models.CharField(blank=True, help_text="Sous quel nom cette personne est connue de l'application, quand ce n'est pas son adresse professionnelle. Laisser vide si les deux coincident.", max_length=150, verbose_name="Identifiant dans l'application"),
        ),
    ]
