# Generated by Django 4.2.28 on 2026-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recolte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='type_prod',
            field=models.CharField(choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe')], default='INTERNE', max_length=10, verbose_name='Type de producteur'),
        ),
        migrations.AlterField(
            model_name='cueillette',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
