# Generated by Django 4.2.28 on 2026-08-24 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(max_length=16, verbose_name='Prefixe')),
                ('annee', models.PositiveIntegerField(verbose_name='Annee')),
                ('valeur', models.PositiveIntegerField(default=0, verbose_name='Valeur')),
            ],
            options={
                'verbose_name': 'Compteur de document',
                'verbose_name_plural': 'Compteurs de documents',
                'db_table': 'compteur_document',
            },
        ),
        migrations.CreateModel(
            name='RegleCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libelle')),
                ('type_document', models.CharField(choices=[('TOUS', 'Tous les documents'), ('ABSENCE', "Demande d'absence / conge"), ('REQUISITION', 'Demande de requisition'), ('SORTIE_CAISSE', 'Sortie de caisse'), ('DEPENSE', 'Depense'), ('MISSION', 'Ordre de mission / perdiem'), ('PRESTATION', 'Prestation'), ('BON_COMMANDE', 'Bon de commande'), ('FORFAIT_COM', 'Forfait de communication')], default='TOUS', max_length=20, verbose_name='Type de document')),
                ('montant_min', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant minimum')),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, help_text='Vide = pas de plafond.', max_digits=14, null=True, verbose_name='Montant maximum')),
                ('role_valideur', models.CharField(blank=True, help_text='Code de role sur cette application : gestionnaire, direction...', max_length=40, verbose_name='Role attendu')),
                ('ordre', models.PositiveSmallIntegerField(default=1, help_text='Position dans le circuit (1 = premier).', verbose_name='Ordre')),
                ('valideur_hierarchique', models.BooleanField(default=False, help_text="L'etape revient au responsable du departement du demandeur, ou a defaut a son rattachement direct.", verbose_name='Revient au responsable du demandeur')),
                ('valideur_identifiant', models.CharField(blank=True, help_text="Identifiant de connexion d'une personne nommement chargee de cette etape. Prioritaire sur le valideur hierarchique et sur le role.", max_length=150, verbose_name='Valideur designe')),
                ('valideur_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du valideur designe')),
                ('nature', models.CharField(choices=[('DECISION', 'Decision'), ('AVIS', 'Avis consultatif'), ('INFORMATION', 'Pour information')], default='DECISION', help_text="Decision : un refus arrete le dossier. Avis : un refus est consigne puis transmis a l'etape suivante. Information : l'etape est franchie a la soumission, le service est seulement tenu au courant.", max_length=12, verbose_name='Nature')),
                ('actif', models.BooleanField(default=True, verbose_name='Regle active')),
            ],
            options={
                'verbose_name': 'Regle de circuit',
                'verbose_name_plural': 'Regles de circuit',
                'db_table': 'regle_circuit',
                'ordering': ['type_document', 'ordre', 'montant_min'],
            },
        ),
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifie le')),
                ('object_id', models.PositiveBigIntegerField()),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libelle')),
                ('role_valideur', models.CharField(blank=True, max_length=40, verbose_name='Role attendu')),
                ('valideur_identifiant', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Valideur attendu')),
                ('valideur_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du valideur')),
                ('nature', models.CharField(choices=[('DECISION', 'Decision'), ('AVIS', 'Avis consultatif'), ('INFORMATION', 'Pour information')], default='DECISION', help_text='Recopiee de la regle au moment ou le circuit est construit.', max_length=12, verbose_name='Nature')),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuve'), ('REJETE', 'Rejete'), ('IGNORE', 'Ignore')], default='EN_ATTENTE', max_length=12, verbose_name='Decision')),
                ('decide_par_identifiant', models.CharField(blank=True, max_length=150, verbose_name='Decide par')),
                ('decide_par_nom', models.CharField(blank=True, max_length=150, verbose_name='Nom du decideur')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de decision')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Etape de validation',
                'verbose_name_plural': 'Etapes de validation',
                'db_table': 'etape_validation',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='compteurdocument',
            constraint=models.UniqueConstraint(fields=('prefixe', 'annee'), name='un_compteur_par_prefixe_et_annee'),
        ),
        migrations.AddIndex(
            model_name='etapevalidation',
            index=models.Index(fields=['content_type', 'object_id'], name='etape_valid_content_220b0d_idx'),
        ),
    ]
