# Generated by Django 4.2.28 on 2026-08-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import prospection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du point de vente')),
                ('type_point', models.CharField(choices=[('BOUTIQUE', 'Boutique'), ('SUPERMARCHE', 'Supermarché'), ('EPICERIE', 'Épicerie / alimentation'), ('RESTAURANT', 'Restaurant / maquis'), ('HOTEL', 'Hôtel'), ('KIOSQUE', 'Kiosque'), ('STATION', 'Station-service'), ('GROSSISTE', 'Grossiste / demi-gros'), ('ENTREPRISE', 'Entreprise / administration'), ('AUTRE', 'Autre')], default='BOUTIQUE', max_length=20, verbose_name='Type de point de vente')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('adresse', models.CharField(blank=True, help_text='Quartier, rue, point de repère.', max_length=255, verbose_name='Adresse / repère')),
                ('contact_nom', models.CharField(blank=True, max_length=150, verbose_name='Contact / responsable')),
                ('contact_tel', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du contact')),
                ('statut', models.CharField(choices=[('PROSPECTE', 'Prospecté'), ('INTERESSE', 'Intéressé'), ('CLIENT', 'Client'), ('PARTENAIRE', 'Point de vente partenaire'), ('A_RELANCER', 'À relancer'), ('REFUS', 'Non intéressé')], default='PROSPECTE', max_length=20, verbose_name='Statut')),
                ('potentiel_ca', models.FloatField(default=0, help_text="Chiffre d'affaires mensuel estimé.", verbose_name='Potentiel commercial (XOF / mois)')),
                ('date_prochaine_relance', models.DateField(blank=True, null=True, verbose_name='Prochaine relance')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_vente', to='distribution.client', verbose_name='Client rattaché')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_prospectes', to=settings.AUTH_USER_MODEL, verbose_name='Commercial en charge')),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de la visite')),
                ('statut_constate', models.CharField(blank=True, choices=[('PROSPECTE', 'Prospecté'), ('INTERESSE', 'Intéressé'), ('CLIENT', 'Client'), ('PARTENAIRE', 'Point de vente partenaire'), ('A_RELANCER', 'À relancer'), ('REFUS', 'Non intéressé')], help_text="Reporté sur le point de vente à l'enregistrement.", max_length=20, verbose_name='Statut constaté')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='Compte rendu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=prospection.models.photo_visite_path, verbose_name='Photo du point prospecté')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude relevée')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude relevée')),
                ('commercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_prospection', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('point_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='prospection.pointvente', verbose_name='Point de vente')),
            ],
            options={
                'verbose_name': 'Visite de prospection',
                'verbose_name_plural': 'Visites de prospection',
                'ordering': ['-date_visite', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='pointvente',
            index=models.Index(fields=['statut'], name='prospection_statut_98dc08_idx'),
        ),
    ]
