# Generated by Django 6.1 on 2026-08-10 14:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=150)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PREPARATION', 'En preparation'), ('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Cloturee')], default='PREPARATION', max_length=12)),
                ('consignes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Campagne d'evaluation",
                'verbose_name_plural': "Campagnes d'evaluation",
                'ordering': ['-periode_debut'],
            },
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('libelle', models.CharField(max_length=120)),
                ('categorie', models.CharField(choices=[('CONGE', 'Conge'), ('ABSENCE', 'Absence'), ('RETARD', 'Retard'), ('PERMISSION', 'Permission')], max_length=12)),
                ('decompte_solde', models.BooleanField(default=True, help_text='Deduit du solde de conges annuel.')),
                ('duree_max_jours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('justificatif_requis', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'absence",
                'verbose_name_plural': "Types d'absence",
                'ordering': ['categorie', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('poids', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='rh.campagneevaluation')),
            ],
            options={
                'verbose_name': "Critere d'evaluation",
                'verbose_name_plural': "Criteres d'evaluation",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('A_FAIRE', 'A faire'), ('AUTO_EVALUATION', 'Auto-evaluation en cours'), ('EVALUEE', 'Evaluee par le manager'), ('VALIDEE', 'Validee RH')], default='A_FAIRE', max_length=16)),
                ('note_globale', models.DecimalField(blank=True, decimal_places=2, help_text='Note ponderee sur 5, calculee a partir des criteres.', max_digits=4, null=True)),
                ('points_forts', models.TextField(blank=True)),
                ('axes_amelioration', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('date_entretien', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rh.campagneevaluation')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_menees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
                'ordering': ['-campagne__periode_debut', 'agent'],
                'unique_together': {('campagne', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=180)),
                ('categorie', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('formateur', models.CharField(blank=True, max_length=150)),
                ('organisme', models.CharField(blank=True, max_length=150)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('places', models.PositiveSmallIntegerField(default=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiee'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='PLANIFIEE', max_length=12)),
                ('departements_cibles', models.ManyToManyField(blank=True, related_name='formations', to='accounts.departement')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=32, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En cours de validation'), ('APPROUVE', 'Approuve'), ('REJETE', 'Rejete'), ('ANNULE', 'Annule'), ('CLOTURE', 'Clotture')], default='BROUILLON', max_length=15)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('demi_journee', models.BooleanField(default=False, help_text="Absence d'une demi-journee seulement.")),
                ('heure_debut', models.TimeField(blank=True, help_text='Pour les retards et permissions horaires.', null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('nb_jours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('motif', models.TextField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/absences/')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('remplacant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplacements', to=settings.AUTH_USER_MODEL)),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='rh.typeabsence')),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demande'), ('CONFIRME', 'Confirmee'), ('REFUSE', 'Refusee'), ('PRESENT', 'Presence confirmee'), ('ABSENT', 'Absent')], default='DEMANDE', max_length=10)),
                ('note_satisfaction', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_suivies', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='rh.formation')),
            ],
            options={
                'verbose_name': 'Inscription a une formation',
                'verbose_name_plural': 'Inscriptions aux formations',
                'ordering': ['-cree_le'],
                'unique_together': {('formation', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='NoteCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('note', models.DecimalField(decimal_places=1, help_text='Note de 0 a 5.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='rh.critereevaluation')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='rh.evaluation')),
            ],
            options={
                'verbose_name': 'Note par critere',
                'verbose_name_plural': 'Notes par critere',
                'ordering': ['critere_id'],
                'unique_together': {('evaluation', 'critere')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PRESENT', 'Present'), ('RETARD', 'En retard'), ('ABSENT', 'Absent'), ('CONGE', 'En conge'), ('MISSION', 'En mission'), ('TELETRAVAIL', 'Teletravail'), ('REPOS', 'Repos / ferie')], default='PRESENT', max_length=12)),
                ('retard_minutes', models.PositiveIntegerField(default=0)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presence',
                'verbose_name_plural': 'Presences',
                'ordering': ['-date', 'agent'],
                'unique_together': {('agent', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee', models.PositiveIntegerField()),
                ('jours_acquis', models.DecimalField(decimal_places=1, default=Decimal('30.0'), max_digits=5)),
                ('jours_reportes', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('jours_pris', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solde de conges',
                'verbose_name_plural': 'Soldes de conges',
                'ordering': ['-annee', 'agent'],
                'unique_together': {('agent', 'annee')},
            },
        ),
    ]
