# Generated by Django 6.1 on 2026-08-10 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeuilValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=120)),
                ('type_document', models.CharField(choices=[('TOUS', 'Tous les documents'), ('REQUISITION', 'Demande de requisition'), ('SORTIE_CAISSE', 'Sortie de caisse'), ('DEPENSE', 'Depense'), ('MISSION', 'Ordre de mission / perdiem'), ('PRESTATION', 'Prestation'), ('BON_COMMANDE', 'Bon de commande'), ('FORFAIT_COM', 'Forfait de communication'), ('ABSENCE', "Demande d'absence / conge")], default='TOUS', max_length=20)),
                ('montant_min', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, help_text='Vide = pas de plafond.', max_digits=14, null=True)),
                ('role_valideur', models.CharField(choices=[('EMPLOYE', 'Employe'), ('MANAGER', 'Manager / Chef de service'), ('RH', 'Ressources Humaines'), ('FINANCE', 'Finance / Comptabilite'), ('DAF', 'Directeur Administratif et Financier'), ('DG', 'Direction Generale'), ('ADMIN', 'Administrateur ERP')], max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=1, help_text='Position dans le circuit (1 = premier valideur).')),
                ('valideur_hierarchique', models.BooleanField(default=False, help_text='Si coche, le valideur est le manager direct du demandeur.')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seuil de validation',
                'verbose_name_plural': 'Seuils de validation',
                'ordering': ['type_document', 'ordre', 'montant_min'],
            },
        ),
        migrations.CreateModel(
            name='CompteurDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixe', models.CharField(max_length=16)),
                ('annee', models.PositiveIntegerField()),
                ('valeur', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de document',
                'verbose_name_plural': 'Compteurs de documents',
                'unique_together': {('prefixe', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('libelle', models.CharField(max_length=120)),
                ('role_valideur', models.CharField(choices=[('EMPLOYE', 'Employe'), ('MANAGER', 'Manager / Chef de service'), ('RH', 'Ressources Humaines'), ('FINANCE', 'Finance / Comptabilite'), ('DAF', 'Directeur Administratif et Financier'), ('DG', 'Direction Generale'), ('ADMIN', 'Administrateur ERP')], max_length=20)),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuve'), ('REJETE', 'Rejete'), ('IGNORE', 'Ignore')], default='EN_ATTENTE', max_length=12)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_decidees', to=settings.AUTH_USER_MODEL)),
                ('valideur_attendu', models.ForeignKey(blank=True, help_text='Renseigne pour les etapes hierarchiques (manager direct).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_a_valider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etape de validation',
                'verbose_name_plural': 'Etapes de validation',
                'ordering': ['ordre', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_etapev_content_9b7d16_idx')],
            },
        ),
    ]
