# Generated by Django 6.1 on 2026-08-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapevalidation',
            name='role_valideur',
            field=models.CharField(choices=[('SALARIE', 'Salarie'), ('RH', 'Ressources Humaines'), ('FINANCE', 'Finance'), ('DIRECTION', 'Direction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seuilvalidation',
            name='role_valideur',
            field=models.CharField(choices=[('SALARIE', 'Salarie'), ('RH', 'Ressources Humaines'), ('FINANCE', 'Finance'), ('DIRECTION', 'Direction')], max_length=20),
        ),
    ]
