# Generated by Django 6.1 on 2026-08-17 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_etapevalidation_role_valideur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seuilvalidation',
            name='valideur_designe',
            field=models.ForeignKey(blank=True, help_text='Personne nommement chargee de cette etape, par exemple le Directeur General pour un dernier mot. Prioritaire sur le valideur hierarchique et sur le role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
