# Generated by Django 6.1 on 2026-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seuilvalidation_valideur_designe'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapevalidation',
            name='avis_consultatif',
            field=models.BooleanField(default=False, help_text='Recopie du seuil : un refus sur cette etape ne bloque pas.'),
        ),
        migrations.AddField(
            model_name='seuilvalidation',
            name='avis_consultatif',
            field=models.BooleanField(default=False, help_text="L'etape recueille un avis : un refus ne bloque pas le dossier, il est consigne et transmis a l'etape suivante, qui tranche. Sans etape suivante, le refus reste bloquant."),
        ),
    ]
