# Generated by Django 6.1 on 2026-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etapevalidation_avis_consultatif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapevalidation',
            name='avis_consultatif',
        ),
        migrations.RemoveField(
            model_name='seuilvalidation',
            name='avis_consultatif',
        ),
        migrations.AddField(
            model_name='etapevalidation',
            name='nature',
            field=models.CharField(choices=[('DECISION', 'Decision'), ('AVIS', 'Avis consultatif'), ('INFORMATION', 'Pour information')], default='DECISION', help_text='Recopie du seuil au moment ou le circuit est construit.', max_length=12),
        ),
        migrations.AddField(
            model_name='seuilvalidation',
            name='nature',
            field=models.CharField(choices=[('DECISION', 'Decision'), ('AVIS', 'Avis consultatif'), ('INFORMATION', 'Pour information')], default='DECISION', help_text="Decision : un refus arrete le dossier. Avis : un refus est consigne puis transmis a l'etape suivante, qui tranche. Information : l'etape est franchie a la soumission, le service est seulement tenu au courant.", max_length=12),
        ),
    ]
