# Generated by Django 6.0.2 on 2026-02-17 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inv', models.DateField(verbose_name='Date inventaire')),
                ('qte_systeme', models.FloatField(default=0, help_text="Stock actuel de l'article dans l'app (ArticleStock.qte_art) au moment de l'inventaire", verbose_name='Quantité système')),
                ('qte_depot', models.FloatField(default=0, help_text="Résultat du comptage physique renseigné par l'utilisateur", verbose_name='Quantité au dépôt')),
                ('ecart', models.FloatField(default=0, help_text='Calculé automatiquement : qte_depot - qte_systeme', verbose_name='Écart')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('BLOQUE', 'Bloqué')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('qualite', models.CharField(blank=True, choices=[('BON', 'Bon'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais')], default='BON', max_length=20, verbose_name="Qualité de l'inventaire")),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='appro.articlestock', verbose_name='Article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_inv'],
            },
        ),
    ]
