# Generated by Django 5.1.15 on 2026-08-28 15:38

import django.db.models.deletion
import planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client planning',
                'verbose_name_plural': 'Clients planning',
                'ordering': ['nom_entreprise'],
            },
        ),
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('vidéo', 'Vidéo'), ('image', 'Image'), ('texte', 'Texte')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Idée de contenu',
                'verbose_name_plural': 'Idées de contenu',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Mensuel'), ('annual', 'Annuel')], max_length=10)),
                ('report_date', models.DateField()),
                ('file', models.FileField(upload_to=planning.models.chemin_rapport_client)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='planning.clientplanning')),
            ],
            options={
                'verbose_name': 'Rapport client',
                'verbose_name_plural': 'Rapports clients',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Shooting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('not_realized', 'Non réalisé'), ('rescheduled', 'Reprogrammé')], default='pending', max_length=20)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournages', to='planning.clientplanning')),
                ('content_ideas', models.ManyToManyField(blank=True, related_name='tournages', to='planning.contentidea')),
            ],
            options={
                'verbose_name': 'Tournage',
                'verbose_name_plural': 'Tournages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('cancelled', 'Annulé'), ('not_realized', 'Non réalisé'), ('rescheduled', 'Reprogrammé')], default='pending', max_length=20)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='planning.clientplanning')),
                ('content_idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='planning.contentidea')),
                ('shooting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='planning.shooting')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PublicationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='planning.clientplanning')),
            ],
            options={
                'verbose_name': 'Règle de publication',
                'verbose_name_plural': 'Règles de publication',
                'unique_together': {('client', 'day_of_week')},
            },
        ),
    ]
