"""
Django settings for JusOrange project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-m5u!=6&_i9%!k#_nu@f4+lsaj)l=a8rlhk1-ums#j=z28+2x2(',  # dev uniquement
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]

# En dev (DEBUG=True) Django autorise déjà localhost ; en production sur le VPS
# la liste est fournie par la variable ALLOWED_HOSTS du fichier .env.
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # API REST
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    # Apps métier
    'recolte.apps.RecolteConfig',
    'appro.apps.ApproConfig',
    'fabrication.apps.FabricationConfig',
    'emballage.apps.EmballageConfig',
    'distribution.apps.DistributionConfig',
    'prospection.apps.ProspectionConfig',
    'entrepot.apps.EntrepotConfig',
    'reporting.apps.ReportingConfig',
    'accounts.apps.AccountsConfig',
    'api.apps.ApiConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # LoginRequiredMiddleware retiré avec les vues templates : l'API applique
    # ses propres permissions (DRF) et l'admin gère son authentification.
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'JusOrange.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'JusOrange.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASE_URL (PostgreSQL du VPS en production), sinon SQLite en dev.
# DB_SSL_REQUIRE reste à False : la base tourne sur la même machine que Django
# et dialogue via localhost, donc le trafic ne quitte jamais le serveur.
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=os.environ.get('DB_SSL_REQUIRE', 'False').lower() in ('true', '1', 'yes'),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# --- Rattachement a GDA Hub ---
#
# Absent en production : Jus d'orange tourne alors seule, avec sa propre
# connexion, exactement comme aujourd'hui. Renseigne par la passerelle du hub,
# il autorise **en plus** le jeton du compte unique. Voir accounts/hub.py.
GDAHUB_JWKS_URL = os.environ.get('GDAHUB_JWKS_URL', '')
GDAHUB_JETON_EMETTEUR = os.environ.get('GDAHUB_JETON_EMETTEUR', 'gdahub-identity')
GDAHUB_JETON_AUDIENCE = os.environ.get('GDAHUB_JETON_AUDIENCE', 'gdahub')

# --- Django REST Framework ---
REST_FRAMEWORK = {
    # L'ordre compte : la classe du hub rend la main des qu'elle voit un jeton
    # qui n'est pas le sien, et les classes maison reprennent derriere elle.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.hub.AuthentificationHub',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.PaginationConfigurable',
    'PAGE_SIZE': 50,
}

# --- CORS (frontend Next.js) ---
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
]
# En production : FRONTEND_URL=https://mon-app.vercel.app
FRONTEND_URL = os.environ.get('FRONTEND_URL')
if FRONTEND_URL:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
CORS_ALLOW_CREDENTIALS = True

# CSRF (admin Django et vues templates derrière HTTPS)
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fichiers envoyés par les utilisateurs (photos de prospection).
# WhiteNoise ne sert que les statiques : en production c'est nginx qui expose
# /media/ directement depuis le disque (voir deploy/nginx-jusorange.conf).
# Les photos de prospection sont servies en adresse absolue : sans prefixe,
# servies sous /jus/ elles pointeraient hors du perimetre de l'application.
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

# Compression + cache-busting des statiques via WhiteNoise
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Sécurité derrière le reverse proxy nginx du VPS.
# nginx transmet le protocole d'origine via X-Forwarded-Proto : sans cet en-tête
# Django croirait que toute requête est en HTTP simple.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Les cookies « HTTPS uniquement » ne s'activent QUE si un certificat est en
# place (ENABLE_HTTPS=True après avoir pointé un domaine et lancé certbot).
# Les activer sur un accès par IP en HTTP rendrait le login impossible.
#
# On ne met volontairement PAS SECURE_SSL_REDIRECT : c'est nginx qui redirige
# http → https, et seulement pour le domaine. Django, lui, ne sait pas
# distinguer le domaine de l'IP : il renverrait aussi l'IP vers
# https://194.163.187.59, adresse pour laquelle aucun certificat n'existe.
# L'accès par IP resterait donc utilisable seulement au prix d'un
# avertissement de sécurité. Le front s'authentifiant par jeton DRF (et non
# par cookie de session), il continue de fonctionner par IP ; seuls l'admin
# Django et la réinitialisation de mot de passe exigent désormais le domaine.
ENABLE_HTTPS = os.environ.get('ENABLE_HTTPS', 'False').lower() in ('true', '1', 'yes')
if ENABLE_HTTPS:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Type de clé primaire par défaut. Les tables ont été créées en BigAutoField
# (valeur par défaut de Django ≥ 5). Le laisser implicite faisait dépendre le
# résultat de la version installée : sous Django 4.2, `makemigrations`
# proposait de repasser toutes les clés en `integer`, ce qui aurait cassé les
# clés étrangères. On fige donc la valeur réellement présente en base.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentification.
# Après connexion sur le formulaire Django, on renvoie vers l'administration :
# l'application métier, elle, se connecte via l'API depuis le frontend React.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = 'login'

# Email (console pour dev - configurer SMTP en production)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'JusOrange GDA <noreply@jusorange.local>'
