# Generated by Django 5.1.15 on 2026-08-28 11:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(max_length=100)),
                ('action_fr', models.CharField(max_length=100, null=True)),
                ('action_en', models.CharField(max_length=100, null=True)),
                ('subject_type', models.CharField(blank=True, max_length=100)),
                ('subject_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('project_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Journal d'activite",
                'verbose_name_plural': "Journaux d'activite",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('client_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('client_en', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planifie', 'Planifie'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('suspendu', 'Suspendu')], default='planifie', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('user_ids', models.JSONField(blank=True, default=list)),
                ('user_names', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('avant', 'Avant'), ('pendant', 'Pendant'), ('apres', 'Apres'), ('securite', 'Securite'), ('qualite', 'Qualite')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='chantiers/photos/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True)),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chantiers.project')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('hidden_from_partner', models.BooleanField(default=False)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='chantiers.project')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('report_date', models.DateField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('weather_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_en', models.CharField(blank=True, max_length=100, null=True)),
                ('page_number', models.CharField(blank=True, max_length=20)),
                ('overall_progress', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('notes_fr', models.TextField(blank=True, null=True)),
                ('notes_en', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='chantiers.project')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='SousPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('hidden_from_partner', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_phases', to='chantiers.phase')),
            ],
            options={
                'verbose_name': 'Sous-phase',
                'verbose_name_plural': 'Sous-phases',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=500)),
                ('activity_fr', models.CharField(max_length=500, null=True)),
                ('activity_en', models.CharField(max_length=500, null=True)),
                ('start_day', models.IntegerField(default=1)),
                ('duration_days', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('hidden_from_partner', models.BooleanField(default=False)),
                ('sous_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='chantiers.sousphase')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('daily_update_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('previous_progress', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('body_fr', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='chantiers.tache')),
            ],
            options={
                'verbose_name': 'Note de progression',
                'verbose_name_plural': 'Notes de progression',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiseAJourJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('report_date', models.DateField()),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('non_demarre', 'Non demarre'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('annule', 'Annule')], default='non_demarre', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_fr', models.TextField(blank=True, null=True)),
                ('comment_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_jour', to='chantiers.tache')),
            ],
            options={
                'verbose_name': 'Mise a jour journaliere',
                'verbose_name_plural': 'Mises a jour journalieres',
                'ordering': ['-report_date', '-id'],
                'unique_together': {('tache', 'report_date')},
            },
        ),
    ]
