# Generated by Django 5.1.15 on 2026-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
