# Generated by Django 6.0.2 - Migration consolidée (ph, refractometre, statut sans Bloquée)

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField()),
                ('numero_of', models.CharField(blank=True, editable=False, max_length=30)),
                ('lavage_effectue', models.BooleanField(default=False)),
                ('filtration_effectuee', models.BooleanField(default=False)),
                ('recette', models.CharField(choices=[('R80_20', '80/20'), ('R75_25', '75/25')], max_length=20)),
                ('eau_ajoutee_l', models.FloatField(default=0)),
                ('sucre_ajoute_kg', models.FloatField(default=0)),
                ('sorbate_ajoute_g', models.FloatField(default=0)),
                ('pasteurisation_80c', models.BooleanField(default=False)),
                ('test_qualite', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme')], max_length=20, null=True)),
                ('ph', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('refractometre', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('volume_final_l', models.FloatField(default=0)),
                ('statut_production', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULLEE', 'Annulée')], default='EN_COURS', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-date_of'],
            },
        ),
    ]
